### PR TITLE
update sumstat merger

### PR DESCRIPTION
**Pull request by changebio**
1. add checking duplicated indels function. And if they exist, remove them.
2. update `snps_match` function to handle duplication case. if duplicated chr_pos or gene_chr_pos exist, run a recursive match for each pair of them between query and subject.
3. test on TWAS sumstats.

### CODE REVIEW

**Comment by gaow** [comment]
@changebio the only request is that please improve the documentation as discussed, of what we did exactly. In particular, please also add a note that we removed the indel ambiguity due to left normalization, although in principle it can be solved with more work we'll leave it for now until we revisit it in time -- links to relevant github issues of our discussion as well as that post i found online should be very helpful. Thanks!

**Comment by changebio** [comment]
improved the documentation.

**Comment by gaow** [comment]
Please include the link to the relevant GitHub discussions, as previously requested

**Comment by changebio** [comment]
> Please include the link to the relevant GitHub discussions, as previously requested

I am not sure what is your meaning? Do you mean to include the link (https://github.com/statgenetics/UKBB_GWAS_dev/issues/81#issuecomment-1015556800) in the pipeline?

**Comment by gaow** [comment]
yes. Direct users there for checking up the depth discussion over that matter to understand the compromise we made here.

**Comment by changebio** [comment]
Okay. I will put it under first notes.

**Pull request merged**
