### PR TITLE
methylation calling module done. Fix issues with RNA_calling

### PR DESCRIPTION
**Pull request by hsun3163**
Add prototype for methylation module.

WIP;
Needs testing and documentation for the rationale.

### CODE REVIEW

**Comment by gaow** [comment]
@hsun3163 I'll review and merge when you are done with it. There are files under `pipeline/` folder they should be cleaned up and not committed here -- you can fix  that in the next commit.

**Comment by hsun3163** [comment]
Unlike what was described in the gdrive dockerfile and the email from Bandita. The package "IlluminaHUmanMehylationEPICanno.ilm10b4.hg19" can not be omitted or avoided by using the attached R package. For the presence of "IlluminaHUmanMehylationEPICanno.ilm10b4.hg19" package is needed by a function embedded deeply of `preprocessQuantile` which was needed for normalization.

Also, installing this package on our cluster failed, for it requires R 4.2.

Therefore, installing it to the docker is required, still waiting for that to be finished.

**Comment by gaow** [comment]
Thanks! So we have to work with hg19 ? Is there a way to  call that bsed on our hg38 reference?

**Comment by gaow** [comment]
Merged to reflect various changes based on feedback from Monday WG meeting.

**Pull request merged**
