### PR TITLE
APA_calling docker image

### PR DESCRIPTION
**Pull request by seriousbamboo**
the basic scripts are included as some other features for aqtl analysis

### CODE REVIEW

**Comment by gaow** [comment]
@seriousbamboo looks good! Can you rename it to `dapars2.dockerfile`?

**Comment by seriousbamboo** [comment]
@gaow Made it. I would test the automatically transformed singularity tomorrow on the cluster.

**Comment by gaow** [comment]
Thanks @seriousbamboo I uploaded the converted singularity def:

https://github.com/cumc/xqtl-pipeline/blob/main/container/singularity/dapars2.def

hope it works! Please remember to upload the MWE data to https://drive.google.com/drive/u/0/folders/1ahIZGnmjcGwSd-BI91C9ayd_Ya8sB2ed

**Comment by seriousbamboo** [comment]
Got it. Thanks, Professor.

**Pull request merged**
