### PR TITLE
Added successful run to fastENLOC notebook

### PR DESCRIPTION
**Pull request by floutt**

### CODE REVIEW

**Comment by gaow** [comment]
Thanks @floutt. @rfeng2023 we will have a merge conflict if we merge this PR as is ... maybe yo ucan take a look and embed the changes to your PR?

**Comment by rfeng2023** [comment]
Hi @floutt . I am currently making some annotations on your notebook. From this PR, it seems like you mainly added the display of output results and the container plugin, right? If that's the case, I will directly copy your displayed results to my notebook. Additionally @gaow , since the container issue hasn't been resolved yet, I'll fix it once more after the container is rebuilt, incorporating all the container information.

**Comment by gaow** [comment]
Thanks @rfeng2023 we have a bit slowdown on our end building the containers ... we are working on that now.

**Comment by gaow** [comment]
Sorry I accidentally merged it when I meant to close. It should be reverted anyways with my other PR and @rfeng2023 should not see merge conflicts. Sorry about that

**Pull request merged**
