### PR TITLE
gene_annotation:convert ProjID to SampleID

### PR DESCRIPTION
**Pull request by al4225**
convert first column to second column: convert ProjID to SampleID

### CODE REVIEW

**Comment by gaow** [comment]
Still, the previouls code assumes `\t` but your updated is `,`. Why don't we stick to `\t`? This seems to be breaking the previous anlaysis code if I merge the change?

**Comment by al4225** [comment]
> Still, the previouls code assumes `\t` but your updated is `,`. Why don't we stick to `\t`? This seems to be breaking the previous anlaysis code if I merge the change?

Cuz the reference data sampleSheetAfterQc.csv is a csv file and uses ','. If we stick to \t, it will return an error.

**Comment by gaow** [comment]
then we should make that an option. parameter input `comma` or `tab` ?

**Comment by al4225** [comment]
yes thanks I can do that.

________________________________
发件人: gaow ***@***.***>
发送时间: 2024年2月26日 17:07
收件人: cumc/xqtl-pipeline ***@***.***>
抄送: Liu, Anjing ***@***.***>; Author ***@***.***>
主题: [EXTERNAL] Re: [cumc/xqtl-pipeline] gene_annotation:convert ProjID to SampleID (PR #873)


then we should make that an option. parameter input comma or tab ?

―

**Comment by al4225** [comment]
Already modified code considering **\t** and **,**.

**Pull request merged**
