### PR TITLE
Modification on APA_impute and Covariate formatting

### PR DESCRIPTION
**Pull request by seriousbamboo**
The new section in data_preprocessing/covariate_formatting.ipynb is designed to merge peer factors generated using the new methods and the covariate file. The apa_impute change the impute workflow from impute then merge to merge and then impute.

### CODE REVIEW

**Comment by gaow** [comment]
@hsun3163 could you review the changes to the covariate formatting code and make comments for improvements? Alternatively you can let me know if I should merge that and you make improvements after i merge -- that might be easier?

**Comment by seriousbamboo** [comment]
@gaow professor, I have talked with hao sun, and he agreed to add the additional part to merge peer factors with covariate data.  I shall comment the improvement made and restart the pull request.

**Comment by gaow** [comment]
Thanks @seriousbamboo you can commit to this PR when you have the changes. I'll review after you commit. (I will receive notifications as u make commits to this PR; no need to start a new one)

**Comment by seriousbamboo** [comment]
Got it. I am polishing the impute code, would push it to hub soon.

**Comment by seriousbamboo** [comment]
@gaow professor, all commits are pushed and commented. Please check.

**Pull request merged**
